### ISSUE TITLE
`readFile` doesn't throw an error when the file doesn't exist

### ISSUE THREAD

**Issue by dfabulich** [ceifa/steamworks.js#36]
`client.cloud.readFile('doesnotexist.txt')` returns the empty string, as if it were a real file with no contents, but it should throw instead. (Or, apropos #35, its promise should be rejected.)

**Comment by ceifa** [comment]
Steam doesn't indicate an error, instead it returns a "file" with 0 size, GetFileSize returns 0 when the file doesn't exists: https://partner.steamgames.com/doc/api/ISteamRemoteStorage#GetFileSize

The way we can do it is checking with `FileExists` method before trying to read, but since the steamworks API is designed that way, I think it should be responsibility of the consumer decide if he wants to check it or not.
