### ISSUE TITLE
macOS NAPI Buffer error

### ISSUE THREAD

**Issue by oyed** [ceifa/steamworks.js#64]
Hi! Just upgraded the library and Electron to 22, however I'm now getting an error on `init` calls;

`Error: Failed to create napi buffer`

**Comment by James226** [comment]
Definitely seeing some of these coming from `getSessionTicket` on M1 chips, but haven't had too much time to look into it yet. Those calls do seem fine on Windows though... (I don't have an Intel Mac to check that variant)

**Comment by James226** [comment]
I've just tried doing a debug build on my M1, and it seems to work fine, so not sure if something has been snuck into napi since the last build (though I can't see anything on the change notes), or perhaps there is an issue in the current build process?

@ceifa might be worth pushing our a fresh build with latest napi, and if we are still having issues on the main build I can try figure whats going wrong..

**Comment by ceifa** [comment]
> I've just raised #66 to bump the compiled version for darwin-arm64 which should stop these errors over there.

@oyed can you confirm you are running into this problem only on apple M1/M2 chips?

> I did notice Github Actions now support M1, so might be nice to get this in at some point!

Nop, no support yet. Only for self-hosted machines.

**Comment by oyed** [comment]
Apple M1 Max @ceifa

**Comment by ceifa** [comment]
Fixed on 0.0.29
